### ISSUE TITLE
Updates listed for apps not installed via YalpStore

### ISSUE THREAD

**Issue by saljut7** [yeriomin/YalpStore#354] opened 2017-12-17 11:41 UTC
### Before creating an issue
1. Make sure you are running the latest version of Yalp Store. Check [here](https://f-droid.org/packages/com.github.yeriomin.yalpstore/).: `YalpStore version 0.32 (F-Droid)`
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue+is%3Aclosed). `/done`

### Expected behaviour
I have installed all apps via F-Droid and no one via YalpStore yet.
YalpStore -> "Settings" -> "Check fpr updates periodically" should have an option to list available updates *only* for apps installed via YalpStore (not for apps installed via F-Droid).

### Actual behaviour
I have installed all apps via F-Droid and no one via YalpStore yet.
YalpStore -> "Settings" -> "Check fpr updates periodically" enables listing available updates for *all* installed apps even though there are no updates for these apps in F-Droid.

Is this possible?
I think F-Droid and PlayStore apps of same developer/project use different signing keys. Could this be used to check from where an app was installed?

### Info about your device
- Samsung Galaxy S2 gt-i9100
- Android 7.1.2 (LineageOS 14.1-2017-12-13-nightly-i9100)

**Comment by yeriomin** [comment] 2017-12-17 14:09
This is a duplicate of #39, #69, #262, #285, #343 

>Search for similar issues here. /done

Your search-fu is weak ;)

**Closed by yeriomin** 2017-12-17 14:09 UTC

**Comment by saljut7** [comment] 2017-12-17 14:41
> Your search-fu is weak ;)

obviously... anyway: so why don't you add a hint below "Check fpr updates periodically" like "If using YalpStore in combination with F-Droid YalpStore will list all updates for apps installed via F-Droid as well and there is currently no way how to excluse F-Droid installed apps automatically. Blacklist apps you installed via F-Droid if this annoys you or you whitelisting for YalpStore apps."

So thanks for https://github.com/yeriomin/YalpStore/issues/343#issuecomment-350423345 !
