### ISSUE TITLE
Update fails due to wrong signature

### ISSUE THREAD

**Issue by tobiasKaminsky** [yeriomin/YalpStore#541] opened 2018-10-12 06:15 UTC
First of all thank you very much for your great app. 
It is a must have if one does not want to use google apps directly!

**Before creating an issue**
1. Make sure you are running the latest version of Yalp Store. Check [here](https://github.com/yeriomin/YalpStore/releases/latest).
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue).
3. Send developer a bug report using Yalp's built-in crash tool. Please identify yourself - the reports are anonymous by default.
4. Number 3 is important. Please do it. It helps a lot.
5. Use the following template to write the text of your issue.

**Expected behavior**
update should work without problem

**Actual behavior**
error message: (roughly translated from german: the new version has a different signing key. you have to remove the old version to install the new one.)

**Steps to reproduce**
1. have booking.com installed in 16.0.
2. see update to 16.1.1
3. click on install an see above error

So I did 
- download the currently installed booking.com app from phone /data/app/com.booking[…]/base.apk
- downloaded 16.0 version from apkmirror
- downloaded 16.1.1 from apkmirror
- ran a apksigner verifiy --print-certs on all three
``` 
base.apk
Signer #1 certificate DN: O=Booking
Signer #1 certificate SHA-256 digest: 6ac8c8a9e6f36e14e52a0a0515a36b7066e720a1b0c8a1b059e0781750a87199
Signer #1 certificate SHA-1 digest: 9c9fbe258a146be83a4a0f1cb64be96a13790324
Signer #1 certificate MD5 digest: e3641de5ae76e3c7a97efcecefe2fe01
com.booking_16.0-8666_minAPI19(arm64-v8a,armeabi,armeabi-v7a,mips,mips64,x86,x86_64)(nodpi)_apkmirror.com.apk
Signer #1 certificate DN: O=Booking
Signer #1 certificate SHA-256 digest: 6ac8c8a9e6f36e14e52a0a0515a36b7066e720a1b0c8a1b059e0781750a87199
Signer #1 certificate SHA-1 digest: 9c9fbe258a146be83a4a0f1cb64be96a13790324
Signer #1 certificate MD5 digest: e3641de5ae76e3c7a97efcecefe2fe01
com.booking_16.1.1-8952_minAPI19(arm64-v8a,armeabi,armeabi-v7a,mips,mips64,x86,x86_64)(nodpi)_apkmirror.com.apk
Signer #1 certificate DN: O=Booking
Signer #1 certificate SHA-256 digest: 6ac8c8a9e6f36e14e52a0a0515a36b7066e720a1b0c8a1b059e0781750a87199
Signer #1 certificate SHA-1 digest: 9c9fbe258a146be83a4a0f1cb64be96a13790324
Signer #1 certificate MD5 digest: e3641de5ae76e3c7a97efcecefe2fe01
```

As you can see, all three have the same signature.

On logcat, I do get this
```
2018-10-12 08:12:22.849 28989-29236/com.github.yeriomin.yalpstore W/PackageParser: Failed to parse /storage/emulated/0/Download/com.booking.8952.apk
    java.io.FileNotFoundException: AndroidManifest.xml
        at android.content.res.AssetManager.openXmlAssetNative(Native Method)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:560)
        at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:528)
        at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1773)
        at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:906)
        at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1294)
        at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:4693)
        at com.github.yeriomin.yalpstore.InstallerAbstract.verify(InstallerAbstract.java:7061)
        at com.github.yeriomin.yalpstore.InstallerBackground.verify(InstallerBackground.java:38)
        at com.github.yeriomin.yalpstore.InstallerPrivileged.verify(InstallerPrivileged.java:93)
        at com.github.yeriomin.yalpstore.InstallerAbstract.verifyAndInstall(InstallerAbstract.java:91)
        at com.github.yeriomin.yalpstore.task.InstallTask.doInBackground(InstallTask.java:1045)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2018-10-12 08:12:22.852 28989-29236/com.github.yeriomin.yalpstore W/InstallerPrivilegedSession: Signature mismatch for com.booking
2018-10-12 08:12:22.871 28989-28989/com.github.yeriomin.yalpstore I/GlobalInstallReceiver: Finished installation (ACTION_PACKAGE_INSTALLATION_FAILED) of com.booking
```

Please let me know, if I can help you debugging this.

**Your setup**
Oneplus 3, lineagoOs, 0.43

**Comment by yeriomin** [comment] 2018-10-14 23:54
I reproduced it with 0.43, but at the time you wrote the issue it was already fixed in master. So please try version 0.44.

**Closed by yeriomin** 2018-10-14 23:54 UTC
Labels: bug

**Comment by tobiasKaminsky** [comment] 2018-10-15 06:02
Thank you for your fix.
I'll try it once it is on Fdroid and re-open if the problem persists.

Thank you for your great software!

**Comment by stemy2** [comment] 2018-11-27 19:00
I have this problem too, and i can't download the 0.44 version since the last version in f-droid repository is 0.43.
