### ISSUE TITLE
Upgrading apps on Oreo removes them from the whitelist

### ISSUE THREAD

**Issue by prurigro** [yeriomin/YalpStore#397] opened 2018-02-15 17:20 UTC
I assume this is behaviour is unique to Oreo as it didn't happen when running Marshmallow, though it could also new related to a more recent update to Yalp. When I install an update for an app it becomes unchecked in the whitelist.

**Comment by yeriomin** [comment] 2018-02-18 13:01
Fixed in master. Thanks for writing an issue.

**Closed by yeriomin** 2018-02-18 13:01 UTC

**Comment by milouse** [comment] 2018-03-15 10:12
I can confirm this issue on Android 6.0.1 too.

@yeriomin, without trying to pressure you that much :/ have you any idea when the 0.36 version will be released? Thanks !

**Comment by yeriomin** [comment] 2018-03-21 22:46
@milouse two-three days more... I made some big internal changes and it made no sense to roll them out gradually as I usually do.

**Comment by momo42** [comment] 2018-03-29 23:54
Its almost 6 weeks now since you fixed this very annoying bug in master. I waited patiently and really don't want to shove but is there an ETA for 0.36? Or can you say us a workaround for this removing behavior in 0.35? Perhaps it would have been better to do such long lasting changes in a separate branch. Anyway thanks for your efforts and for this great app!
