### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Schekolda** [yeriomin/YalpStore#22] opened 2017-01-03 03:53 UTC
I have a question: can you bring back support for downloading paid apps if this worked?

**Comment by 1337sup3rh4x0r** [comment] 2017-01-04 13:19
duplicate of #8

**Comment by yeriomin** [comment] 2017-01-12 23:04
Closing as a duplicate of #8.
I might do this, but I still don't think it is a good idea. Apps like Yalp, racoon and so on violate Google ToS and Google might ban your account, taking your paid apps away.

**Closed by yeriomin** 2017-01-12 23:04 UTC
