### ISSUE TITLE
No apps need to be updated

### ISSUE THREAD

**Issue by GGGunrunner** [yeriomin/YalpStore#428] opened 2018-04-23 15:29 UTC
Running on Galaxy Note 4 with Marsh 6.0.1

It's been working perfectly since I've installed it 5 or 6 months ago.
But few days ago whenever I press "Check for updates" - it comes up with

"No apps need to be updated"

While there's in fact tons of updates. Any remedy?

**Comment by ale5000-git** [comment] 2018-04-23 15:32
You need to update to version 0.39.

**Comment by GGGunrunner** [comment] 2018-04-23 15:51
Thanks! I was on 0.38

It worked. Can mark this as SOLVED.

**Comment by yeriomin** [comment] 2018-04-23 19:43
Duplicate of #422...

**Closed by yeriomin** 2018-04-23 19:43 UTC
Labels: duplicate
