### ISSUE TITLE
[Request] Allow download of incompatible apps

### ISSUE THREAD

**Issue by YogliB** [yeriomin/YalpStore#103] opened 2017-03-11 18:54 UTC
I could be an optional thing.

Thanks.

**Comment by yeriomin** [comment] 2017-03-11 22:19
Every app which can be downloaded is allowed to be downloaded. If it is marked as incompatible, it means that Play Store does not return info which is required to download the app. Sorry.

Also, this is a duplicate of #59 and #75.

**Closed by yeriomin** 2017-03-11 22:19 UTC
