### ISSUE TITLE
Doesn't download application

### ISSUE THREAD

**Issue by theo546** [yeriomin/YalpStore#400] opened 2018-02-17 17:25 UTC
### Expected behaviour
Download the application.

### Actual behaviour
Stuck and does nothing
Tried deleting all app data, restarted phone.

### Steps to reproduce
Just download an app

### Info about your device
Device model, android falvour
Lenovo K3 Note, Android 7.1.2_r29 - Ressurection Remix v5.8.4

**Comment by yeriomin** [comment] 2018-02-18 13:02
Please, read the https://github.com/yeriomin/YalpStore#faq. If it doesn't help, reproduce the problem and send me a bug report through Yalp Store UI with your name. Or attach logs here.

**Comment by theo546** [comment] 2018-02-18 17:02
I'm gonna get back to you with a log file once the bug happen get, it seem to be random

**Comment by yuukiw** [comment] 2018-04-13 04:55
Do you happen to use apkpure too. I noticed that the app tends to clock up the android download Manager so it won't download anything. I force closing it helps (even if you yourself didn't launch it)

**Comment by yeriomin** [comment] 2018-04-15 22:12
@theo546 This looks like a problem with your DownloadManager. The [FAQ](https://github.com/yeriomin/YalpStore#faq) should help. If you have any more info, please provide it. Meanwhile I'm closing this.

**Closed by yeriomin** 2018-04-15 22:12 UTC
