### ISSUE TITLE
Can't write non-digit characters for versions on Manual Download activity

### ISSUE THREAD

**Issue by HorlogeSkynet** [yeriomin/YalpStore#373] opened 2018-01-19 15:31 UTC
Hi there ! 🙂 

(No logs 'cause it's just a text box)

### Expected behaviour
Being able to write `4.3.9` (for instance)

### Actual behaviour
We could only write `439` (copy/paste does not work either)

### Steps to reproduce
1. Choose an "incompatible" application
2. Try to write a semantic versioning value
3. Loop with `2`

### Info about your device
Samung i9305 Android 7.1.2

Bye, thanks for your time 👋

EDIT : I suppose it's due to `number` present [here](https://github.com/yeriomin/YalpStore/blob/71ba67e47c963a2e14d268a07771e7e3bd62c91a/app/src/main/res/layout/manual_download_activity_layout.xml#L48) 🤔

**Comment by yeriomin** [comment] 2018-01-20 15:51
This is expected behavior. The message on the manual download screen states several times that version **code** is expected and that it is a number.

What translation are you using? Maybe the message is not clear. Please fix the message if you can on the [Yalp Store translation page](https://poeditor.com/projects/po_edit?order=&filter=&id=95185&id_language=189&search=manual_download_warning).

Also, it is a duplicate of #129.

**Closed by yeriomin** 2018-01-20 15:51 UTC

**Comment by HorlogeSkynet** [comment] 2018-01-20 17:28
Sorry for duplicate, it was a misunderstanding...

I've tried from `1` to `100` and couldn't get a match, so I thought a semantic version was expected in my case
