### ISSUE TITLE
Blacklisting (ignore updates) apps not persisting

### ISSUE THREAD

**Issue by KehrBehr** [yeriomin/YalpStore#427] opened 2018-04-23 14:59 UTC
### Expected behaviour
After blacklisting an application, it should remain blacklisted until manually un-blacklisted

### Actual behaviour
After blacklisting an application, if you force close Yalp Store and re-open, that application is no longer blacklisted.

If you blacklist an application, then run a check for updates, then force close Yalp Store and re-open, the blacklisting will persist as it should.

As a side note, if you blacklist the Yalp Store application, then no matter if you check for updates or not,  the Yalp Store, and all other applications blacklisted in that same session, will no longer be blacklisted after force closing and re-opening Yalp Store.

### Steps to reproduce
1. Open Yalp Store
2. Blacklist application (ignore updates) via long hold or 3 dot menu
3. Force close Yalp Store
4. Re-open and application is not blacklisted

### Info about your device
Nexus 5X 
CopperheadOS 
Android 8.1.0

Yalp Store 0.38

**Comment by yeriomin** [comment] 2018-04-23 21:36
Cannot reproduce.

Are settings saved properly? Are you sure your data partition is writable and has enough (non-zero) space? Maybe your OS is modified somehow? Logs might help.

**Comment by KehrBehr** [comment] 2018-04-24 00:59
So I'll have to keep messing around with it because I'm getting some weird behaviour that I can't fully test right now, but just to give some more info.

I just went and uninstalled Yalp Store, and reinstalled (from F-Droid).  I was able to blacklist AntennaPod (Open Yalp Store, ignore updates, force close, re-open Yalp Store) just fine.  But It seems I can't blacklist any others (at least the few I tried) unless I do the check for updates workaround I mentioned above.  I even blacklisted several apps when I blacklisted AntennaPod, but only AntennaPod remained blacklisted after a force close.  It is the first app that is displayed in my list of apps if that is relevant.

I did use the "Report an issue" feature in the app early today.  I think I put "KehrBehr" in the optional section, and mentioned that I posted on GitHub.  If something didn't go through, let me know and I can resubmit.

If you still can't reproduce, I'll look more into it, and see if there's just something wrong with my setup.

**Comment by radasbona** [comment] 2018-04-28 18:49
I have the same issue.
Long time ago blacklisted apps stay on the list.
But since 5 Days i try to blacklist "open camera", no chance. 

Android 7.1.2 
Yalp Store 0.38

**Comment by yeriomin** [comment] 2018-05-02 00:50
@KehrBehr @radasbona I assume the problem is with force-closing Yalp Store. Yalp Store stores blacklist in SharedPreferences. The exact moment when the info is written to disk is not decided by the app developer and might happen when the OS feels like it. Force closing can only be enabled to developer settings, it is not a tool for an ordinary user, it does not guarantee predictable app behavior. App developer can not and should not account for force-closing.

If the black list does not work during normal workflow, it is a bug. Otherwise, I'm closing this.

**Closed by yeriomin** 2018-05-02 00:50 UTC
