### ISSUE TITLE
[Feature Request] Writing reviews

### ISSUE THREAD

**Issue by leopard20** [yeriomin/YalpStore#440] opened 2018-05-05 07:12 UTC
Can you please add the ability to write reviews? It's the only thing missing IMO.

Also, can I log in using my own Google account?

**Comment by yeriomin** [comment] 2018-05-05 21:04
This is a duplicate of #14.

> Can you please add the ability to write reviews?

You can do it as long as you use your own account. To use your own account choose "Log out" in the main menu.

**Closed by yeriomin** 2018-05-05 21:04 UTC
Labels: duplicate
