### ISSUE TITLE
Device spoofing doesn't work

### ISSUE THREAD

**Issue by anon-73** [yeriomin/YalpStore#151] opened 2017-04-28 00:46 UTC
### Expected behaviour
After changing the section "pretend to be a different device" and logging out, logging in back should work as expected.

### Actual behaviour
After changing the section "pretend to be a different device", I'm unable to re-login. Got trapped in a loop constantly asking me to enter login and password, despite filling the fields correctly.

### Steps to reproduce
1. Open app
2. Open settings
3. Change the  "pretend to be a different device" option to something else
4. Log-out
5. Log in back (tried with Yalp's credentials and my own, both failed)

### Info about your device
Android 7.1.2, Xiaomi RN3P

**Comment by syl3nt** [comment] 2017-04-28 00:49
Checking if it happens to me to, i have the same device as you

**Comment by syl3nt** [comment] 2017-04-28 00:53
OK, 
i selected htc .. 10 , logged out, opened app, trying to log in with yalp store account, and it goes back to the same screen (login with witch account screen) and doesn't login
so it doesn't happen just with him, i have exactly the same device as him, and android version as well.

**Comment by yeriomin** [comment] 2017-04-28 01:18
It's a duplicate of #128. Fixed in master.

I know I should tag v0.14 faster, but I started implementing features related to system apps and they don't make much sense if not done together. I will probably tag v0.14 on the weekend.

**Closed by yeriomin** 2017-04-28 01:18 UTC
