### ISSUE TITLE
Feature request: list only app installed via YalpStore

### ISSUE THREAD

**Issue by tecufanujacu** [yeriomin/YalpStore#262] opened 2017-08-25 09:08 UTC
I'd like to have a filter to hide apps not installed via yalp store, for example the app installed via fdroid.

**Comment by yeriomin** [comment] 2017-08-25 12:31
Duplicate of #39, #69 and several others.

It is impossible to reliably detect app's source before installation attempt. Sorry.

**Closed by yeriomin** 2017-08-25 12:31 UTC
