### ISSUE TITLE
"Incorrect email or password"

### ISSUE THREAD

**Issue by temtemy** [yeriomin/YalpStore#299] opened 2017-10-10 01:19 UTC
### Expected behaviour
Being able to login using Yalp's built-in fake account

### Actual behaviour
It returned instead an error: "Incorrect email or password"

### Steps to reproduce
1. Download the latest version of Yalp Store (version 0.27) from F-Droid.
2. Open Yalp Store.
3. The error should be seen.

### Info about your device
I am using Samsung Galaxy S3, Android 7.1.2, the custom ROM is Resurrection Remix 5.8.5, rooted, and no GAPPS installed.

**Comment by temtemy** [comment] 2017-10-10 01:20
When I downgraded Yalp Store to version 0.26, it became worse. It crashes when I open it.

**Comment by dartraiden** [comment] 2017-10-10 04:54
0.26 cannot work with built-in fake account

**Comment by thrillfall** [comment] 2017-10-10 09:29
I have the same problem with a fresh install of 0.27 on a rooted LineageOS 14.1 (cedric). 

Meanwhile i have no problems on my other device. Though i did not dare to logout and login again on that one.

**Comment by killoid** [comment] 2017-10-10 13:40
same problem faced here while i freshly installed the latest version on lineageos 14.1.

**Comment by auroszx** [comment] 2017-10-10 18:11
I don't have this issue on my Nexus 7 running AOSP 7.1.2 (no gapps installed), but I do have it on my LG P500 running CM10 (4.1.2, also no gapps installed).

**Comment by yeriomin** [comment] 2017-10-10 18:24
This is a duplicate of #297.

In short: 0.28 attempts to fix this, but since it depends on an external service, it is not guaranteed.

**Comment by wine** [comment] 2017-10-17 10:04
@yeriomin 
Hi! I'm trying to use Yalp Store 0.28 (F-Droid build) with a real Google account, inserting the email and password. It works perfectly for a while, then it logs off with a "Incorrect email or password" error. If I try to re-login, it works again before doing the same. It sounds like a session expiration or similar. Device is running Android 6.0.1

**Comment by Primokorn** [comment] 2017-10-18 13:28
@wine Same issue here. I recently activated 2FA for my Gmail accounts.
Do you also have it enabled?

**Comment by killoid** [comment] 2017-10-18 13:53
@Primokorn i also faced the same issue but i haven't activated 2FA.

**Comment by wine** [comment] 2017-10-18 14:22
@Primokorn 
No, I'm not currently using 2FA in the account.

More info:
- Enabling the "less secure apps" option in the security settings did nothing
- I noticed that even built-in accounts are disconnecting after a few minutes

**Comment by dimqua** [comment] 2017-10-18 17:03
The same error here. I can't to login with my own account also. 

LineageOS 14, Yalp 0.28.

**Comment by andreazorzetto** [comment] 2017-10-20 22:46
Same problem here with Galaxy S7, fresh installation of Yalp 0.28 on different roms (aosp and stock based).
But none of them resolved the intermittent authentication failures with fake and my own about. Most of the times the solution is to close the app and try again. Also tired to change the device identification with no success. 
I'm a bit sad since I learnt to rely a lot on Yalp and it's been working for ages on my old galaxy note 3 with absolutely no problems.

**Comment by andreazorzetto** [comment] 2017-10-24 06:50
I'd like to add to this behaviour that I ended up entering my own personal credentials into yalp. They work for a while but after some hours I don't get any more updates and if I try a search I'm asked again to enter credentials (that I never remember since they were the specific app credentials I create for yalp).

**Comment by Primokorn** [comment] 2017-10-24 07:29
I disabled AdAway to see if it can help as mentioned on [XDA](https://forum.xda-developers.com/showpost.php?p=74233229&postcount=10039).
Are you also using AdAway (or other sources to manage your hosts file)?
Disconnecting and connecting again also works to get Yalp working again.

**Comment by Peremptor** [comment] 2017-10-27 09:58
I now uninstalled Yalp. Sorry, but for Google it doesn't seem to matter now if you use your own account or the fake one. Yalp simply doesn't work for me shortly after I installed LineageOS on my Honor 5X.
I'm very sad about Google forcing users to use only their service. And it's by no means a service because you can't download any apk. I think other sites will have to shut down sooner or later just because of f.ing Google -.-

**Comment by micressor** [comment] 2017-10-31 06:26
Same at LineageOS (Android 7.1.2) with Yalpstore 0.28. I had to click several times until I got a valid token.

**Comment by Krawei** [comment] 2017-11-01 08:12
Same here with v0.28. I don't get a valid token, and Yalp tells me a the failure alrt with the invalid credentials m tioned above, plus network wrrors (I have a rock solid wifi connection) or something about java exception connecting to github.io.

Please fix this. Mabe you can use kind of a "load balancer" with different accounts? 

Kind Regards,

Krawei

**Comment by yeriomin** [comment] 2017-11-03 16:09
@wine @Primokorn @killoid @dimqua @andreazorzetto @Peremptor @micressor @Krawei A couple of weeks ago there was a change in Google API. Auth token which is used to sign requests to the Google API is now short-lived. This is not connected to the token dispenser hosting change. The token dispenser problem has been resolved for some time.

Please refer to #311 about forced relogins.

**Closed by yeriomin** 2017-11-03 16:09 UTC
