### ISSUE TITLE
Feature Request: Adding Option to sort search results by rating and number of users.

### ISSUE THREAD

**Issue by mikhoul** [yeriomin/YalpStore#331] opened 2017-11-25 01:39 UTC
First Thanks for this very useful app 👍  

I'd really like to have the option to sort the search results by their **"rating**" (stars) and also by the "**number of users**".

Would it be possible to add those 2 criteria ?  

Regards :octocat:

**Comment by yeriomin** [comment] 2017-11-27 16:36
I'm glad you find it useful!

Unfortunately, sorting search results is impossible. The Google API does not support it, the only thing I can do is request the next portion of results. And sorting it on the client side requires knowing *all* the apps in Play Store.

Also, this is a duplicate of #201 and #253.

**Closed by yeriomin** 2017-11-27 16:36 UTC

**Comment by mikhoul** [comment] 2017-11-27 23:16
Hi @yeriomin ,

OK I understand but I have at least an idea to have only the results with rating over 3.9 : 

You could use `display:none` to hide all the results that are don't begin by 4 so we would just see the results between 4 and 5.   

Every results between 1 and 3.9 would be hidden via CSS with `display:none` .

It should be fairly easy to implement since it would be mostly based on CSS, what do you think of this idea ?

**Comment by yeriomin** [comment] 2017-11-28 12:44
@mikhoul The filter can be done. Its going to be hard to make it useful, though. Note: most (80-90%) app ratings in the search are 4 - 4.5 stars. Finding apps with 5 or 3 is almost impossible. Maybe filtering by number of installations can be useful.

But why do you think it has anything to do with CSS? Yalp Store does not parse Play Store web interface.

**Comment by mikhoul** [comment] 2017-11-28 16:13
@yeriomin   I' m new to "programming" so maybe I'm wrong...  😉 

I was thinking that you call some API on Google Store and receive the data (all the text of each entry) and that you made a CSS template in your program to display it in a more useful/elegant way than the Google playstore.

Since all the entry come directly from the Google API I was thinking you can't filter it since you did not receive all the results... and one way to do it without removing any Apps entry from the list would be to just "hide" the entry via CSS using an "observer"  that watch for any entry that have a score lower than 4.

**Right now** writing this I see that "my solution" is **to complicated for nothing** and was "**wrong**"because you could just remove/filter the entry before it is rendered to Yalp GUI instead of rendering it and remove it after via "display:none".

**Why I was thinking in a such complicated way:** Because I had in my mind that you can't change the data from the API for sorting the results via their ratings since you don't receive all the results in one request. So I was trying (in a wrong way) to find a solution for a problem that did not exist since we don't have to sort ALL the results but only **hide** those that are not relevant and **not** sorting them. 😛

I'm new to Android and search for a lot of  various Apps not only the popular one so I find myself with a lot of apps of low quality rated 2-3 in the results so IMO it would be useful to be able to filter/remove those. 

But at the same time I agree with you that being able to filter the results  by number of installations would be also very useful especially for the categories that are the most popular and that return many many results. 

**Another thing** that I think could be done that would be very useful when searching for a new app in the store would be to have highlighted in the results (without having to go in the description of the app) the date of the last update of the app.

This way we can quickly discriminate between apps that are no longer maintained and apps that have received recent updates.  In Gihub when I search for a program I use this criteria  (last update) to save me time and prioritize projects that are "active" and maintained. 

Since in the Google playstore we can't sort the app by the latest update date we could at least put it in the main description (if available) and highlight it, it would help a lot to spot the actively developed apps.

Usually the updated date is always at the same place in the description in the "ADDITIONAL INFORMATION" section: https://i.imgur.com/8GzN3hW.png  so it would be easy to retrieve/parse it. 

**Have a nice day !** :octocat:

**Comment by yeriomin** [comment] 2017-11-28 17:47
> CSS
> display:none

Yalp Store is a Java app, running on Android. CSS is used to style web pages which are shown by a web browser. These things are not related.

> date of the last update of the app

Yes, this could be useful, but search output is already giving too much information. It is difficult to perceive. Another thing which could be useful there is download size. Adding these things would require UI rewrite.

> Usually the updated date is always at the same place in the description

It is already shown in Yalp Store on the app details page and in the updates list.

Thank you for your suggestions, I am going to keep them in mind.

Regards.
