### ISSUE TITLE
[REQUEST] Download path selection

### ISSUE THREAD

**Issue by achanu** [yeriomin/YalpStore#77] opened 2017-02-23 11:06 UTC
Hi, it could be useful to be able to change download path.

A use case example, would be auto install apk by tasker and purge download older file.
Or simply purge downloaded APK without manipulate other downloaded file.

Regards

**Comment by yeriomin** [comment] 2017-02-23 11:35
Deleting apk after installation is already implemented in master. Closing as duplicate of #65.

**Closed by yeriomin** 2017-02-23 11:35 UTC
