### ISSUE TITLE
Suggestion: sorting apps

### ISSUE THREAD

**Issue by fmcgorenc** [yeriomin/YalpStore#391] opened 2018-02-06 20:05 UTC
I think it would be cool if we could sort apps based on apk size, play store star rating, name... For example if you're looking for a smaller app that takes less storage space or something.

**Comment by whyorean** [comment] 2018-02-07 03:56
Its already there

**Comment by fmcgorenc** [comment] 2018-02-07 09:56
Really? Can't find any option to sort apps based on apk size. And for star rating there's only filtering, not sorting.

**Comment by yeriomin** [comment] 2018-02-18 12:59
This is a duplicate of #201, #253, #331.

In short: Play Store API does not support things required to implement this.

**Closed by yeriomin** 2018-02-18 12:59 UTC
Labels: duplicate
