### ISSUE TITLE
option: check/download updates only on wifi

### ISSUE THREAD

**Issue by ilf** [yeriomin/YalpStore#203] opened 2017-06-18 21:37 UTC
Yalp currently does not distinguish between data connection and wifi. F-Droid has a nice setting "Only on Wi-Fi" - it would be really cool to have something like this in Yalp.

Thanks, and keep up the good work!

**Comment by yeriomin** [comment] 2017-06-22 18:01
Duplicate of #189.

**Closed by yeriomin** 2017-06-22 18:01 UTC
Labels: duplicate

**Comment by ilf** [comment] 2017-06-23 07:14
Sorry, I promised I searched before I posted. :) Thank you!
