### ISSUE TITLE
Bug with Tricount update

### ISSUE THREAD

**Issue by Cotopaxi42** [yeriomin/YalpStore#216] opened 2017-06-29 13:18 UTC
### Expected behaviour
Yalp Store should download the last version of the Tricount app (it worked perfectly before the last version).

### Actual behaviour
I have an error: "Network error: com.github.com.yeriomin.playstoreapi.GooglePlay Exception Server error". And no download of the app. 
No problem with other apps like Here, for exemple.

### Info about your device
Cyanogen Mod 13, Moto G

**Comment by marat1995** [comment] 2017-06-29 13:25
@Cotopaxi42 try to clean Yalp's data

**Comment by Cotopaxi42** [comment] 2017-06-29 13:32
How? I uninstalled/reinstalled Yalp Store but the problem is still here.

**Comment by marat1995** [comment] 2017-06-29 13:45
@Cotopaxi42  Do you use Yalp 0.18?

**Comment by Cotopaxi42** [comment] 2017-06-29 13:47
Yes, last version.

**Comment by marat1995** [comment] 2017-06-29 13:48
@Cotopaxi42 The full app's name is Tricount - Split group bills?

**Comment by Cotopaxi42** [comment] 2017-06-29 13:50
Yep. :)

**Comment by marat1995** [comment] 2017-06-29 13:55
@Cotopaxi42 wtf
Google said last version is 2.5.2
Yalp too.

**Comment by Cotopaxi42** [comment] 2017-06-29 13:58
I know. On my device I have version 2.5.1 but when I want to install the last one, to update, I can't, Yalp won't download the update and I have the error message of the first post.

**Comment by marat1995** [comment] 2017-06-29 14:01
@Cotopaxi42 have you root permision?
if you have, you can copy tricount's folder (/data/data and tricount)
and then you can uninstall tricount app and download it again.
Then you should to copy yours saving data to /data/data and tricount

**Comment by Cotopaxi42** [comment] 2017-06-29 14:14
I uninstalled the app but I can't install it again, same error... 
And Yes I have root. 
Weird..

**Comment by marat1995** [comment] 2017-06-29 14:28
@Cotopaxi42 you can install app from site.

**Comment by Cotopaxi42** [comment] 2017-06-29 14:35
Can't find it. Thanks anyway.

**Comment by marat1995** [comment] 2017-06-29 14:43
@Cotopaxi42 green button near red button.

**Comment by Cotopaxi42** [comment] 2017-06-30 12:55
Can't find it and can't download the app via Yalp. Can anyone reproduce the bug ?

**Comment by yeriomin** [comment] 2017-06-30 13:10
@Cotopaxi42 Hi. Just downloaded the app you mentioned. Could not reproduce the problem. Can *you*?

Network error means the problem happened on server side and might go away on its own.

**Comment by Cotopaxi42** [comment] 2017-06-30 14:23
Yep, problem still here for me. It's ok, I will wait. :)

Thanks!!

**Comment by yeriomin** [comment] 2017-06-30 16:02
@Cotopaxi42 Its been more than a day, it shouldn't take that long. If 0.17 works but 0.18 doesn't, it is a bug. Could you check?

Also, please send me a bug report. You can do it by clicking on developer's email on the About page. Yalp logs and your device info will be attached to the letter automatically. Add your username or a link to this page so that I would know it is you.

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Cotopaxi42** [comment] 2017-06-30 17:21
It doesn't work with Yalp 0.17 or 0.18, same error, I tried. Ok for the bug report.

**Comment by yeriomin** [comment] 2017-07-31 15:36
@Cotopaxi42 I think the app's developer might have changed its compatibility settings, so it is *no longer* compatible with your device. But that's just a guess.

The issue is quite old, and no one reported anything similar, so I'm closing it. Please message me if you have anything to add.

**Closed by yeriomin** 2017-07-31 15:36 UTC
