### ISSUE TITLE
Missing region-locked apps

### ISSUE THREAD

**Issue by bigretromike** [yeriomin/YalpStore#107] opened 2017-03-16 12:57 UTC
### Expected behaviour
When looking for "Miitomo" (https://play.google.com/store/apps/details?id=com.nintendo.zaaa) or going to Nintendo Co., Ltd. other apps and check all apps I should see Miitomo

### Actual behaviour
When looking for Miitomo - which isn't global available there is no info about app existence. 

### Steps to reproduce
1. Be in affected country (ex. Europe - Poland )
2. type "Miitomo" in search
3. No results about real app

### Info about your device
LineageOS 14.1

Is region lock in app store by ip ?

**Comment by yeriomin** [comment] 2017-03-16 19:38
As far as I know there is no 100% reliable solution to this. The solutions include:
* getting an ip from the country where the app is available
* faking your mobile operator
* changing your billing address and making at least 1 purchase

These things work for some people and don't work for others. Also, all of these things cannot be implemented in Yalp. Sorry.

Also, this is a duplicate of #52.

**Closed by yeriomin** 2017-03-16 19:38 UTC

**Comment by bigretromike** [comment] 2017-03-16 20:25
I wasn't sure if it was account or ip based. Atill thanks for alternative ;-)

**Comment by Kara-ism** [comment] 2017-09-10 15:25
@yeriomin
Is it possible to download region-locked Apps with a billing-address-filled account?

For further explanation, an free App is limited to download in A country, and there's a billing address filled as B country of an account.
Thus this account is locked as B region.

In this situation, Yalp can't download that App with this specific account right away, even VPN of Country A is enabled.
Well, will this getting tweaked in future?

There was a working project called “Apk Downloader” ,which let accounts (even an billing address filled as another country) to download Apps without 
 any regional restrictions unitl June,2017.
I think the developer is abandoned this project because that is not updated for over 3 years.

Here's the link: https://github.com/jackpf/ApkDownloader

I fully appreciate your work and excuse for my poor English. :smile:

**Comment by yeriomin** [comment] 2017-09-13 14:37
@Kara-ism Sorry, I can only repeat what I've said earlier in this issue. I don't know of a way to implement this except external tools.

The project you mentioned is interesting but uses a very old API endpoint, which is no longer used by real devices. For me it didn't download anything. The way used there can not be implemented in Yalp Store.
