### ISSUE TITLE
Network Not working on fdroid version

### ISSUE THREAD

**Issue by v1nc** [yeriomin/YalpStore#448] opened 2018-05-18 13:51 UTC
It always says "no network" when using the latest fdroid version. With latest github release, everything works fine.

**Comment by ArchangeGabriel** [comment] 2018-05-18 13:52
That’s normal, F-Droid did not pick the latest version yet (it was only tagged some hours ago).

**Comment by yeriomin** [comment] 2018-05-18 13:57
Duplicate of #447. Fixed in version 0.41.

**Closed by yeriomin** 2018-05-18 13:57 UTC
Labels: bug, duplicate, google api change
