### ISSUE TITLE
Yalp Store terminates when opening settings

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#47] opened 2017-01-30 17:37 UTC
Since version 0.5 it terminates when opening settings

**Comment by yeriomin** [comment] 2017-01-30 18:06
Cannot reproduce. Please give more details when you write a bug report. Example of a good bug report: #37.

**Comment by teod0r** [comment] 2017-01-30 18:26
> logcat|grep -i yalp
I/Timeline(  979): Timeline: Activity_launch_request id:com.github.yeriomin.yalpstore time:113507
I/ActivityManager(  682): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.yeriomin.yalpstore/.UpdatableAppsActivity} from pid 979
I/ActivityManager(  682): Start proc com.github.yeriomin.yalpstore for activity com.github.yeriomin.yalpstore/.UpdatableAppsActivity: pid=1955 uid=10144 gids={50144, 1028, 1015, 3003}
D/ActivityThread( 1955): handleBindApplication:com.github.yeriomin.yalpstore
I/ActivityManager(  682): Displayed com.github.yeriomin.yalpstore/.UpdatableAppsActivity: +581ms
I/Timeline(  682): Timeline: Activity_windows_visible id: ActivityRecord{651bffb8 u0 com.github.yeriomin.yalpstore/.UpdatableAppsActivity t6} time:114253
I/com.github.yeriomin.yalpstore.UpdatableAppsActivity$1UpdatableAppsTask( 1955): Ignoring updates for ch.blinkenlights.android.vanilla isBlacklist=true inList=true
I/com.github.yeriomin.yalpstore.UpdatableAppsActivity$1UpdatableAppsTask( 1955): Ignoring updates for org.y20k.transistor isBlacklist=true inList=true
I/com.github.yeriomin.yalpstore.UpdatableAppsActivity$1UpdatableAppsTask( 1955): Ignoring updates for org.brandroid.openmanager isBlacklist=true inList=true
I/com.github.yeriomin.yalpstore.UpdatableAppsActivity$1UpdatableAppsTask( 1955): Ignoring updates for com.goodmooddroid.gesturecontroldemo isBlacklist=true inList=true
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for org.csploit.android
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for com.example.android.monthcalendarwidget
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for bander.notepad
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for com.perm.kate
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for ru.fourpda.skins.dark
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for org.schabi.newpipe
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for com.brewcrewfoo.performance
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for com.robert.maps
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Skipping non-free app net.osmand.plus
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Skipping non-free app acr.browser.lightning
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for org.adaway
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Skipping non-free app com.elsdoerfer.android.autostarts
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for net.i2p.android.router
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for starcom.snd
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for com.vonglasow.michael.satstat
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for com.github.yeriomin.yalpstore
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for com.intelliswift.pdf
I/com.github.yeriomin.yalpstore.PlayStoreApiWrapper( 1955): Empty response for org.fdroid.fdroid
I/Timeline( 1955): Timeline: Activity_launch_request id:com.github.yeriomin.yalpstore time:118521
I/ActivityManager(  682): START u0 {cmp=com.github.yeriomin.yalpstore/.PreferenceActivity} from pid 1955
E/ActivityThread( 1955): 	at com.github.yeriomin.yalpstore.PreferenceActivity.onCreate(PreferenceActivity.java:36)
E/ActivityThread( 1955): 	at com.github.yeriomin.yalpstore.MultiSelectListPreference.onGetDefaultValue(MultiSelectListPreference.java:220)
E/ActivityThread( 1955): 	at com.github.yeriomin.yalpstore.MultiSelectListPreference.<init>(MultiSelectListPreference.java:32)
E/AndroidRuntime( 1955): Process: com.github.yeriomin.yalpstore, PID: 1955
E/AndroidRuntime( 1955): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.yeriomin.yalpstore/com.github.yeriomin.yalpstore.PreferenceActivity}:

**Comment by teod0r** [comment] 2017-01-30 18:29
samsung galaxy tab 4 10.1 cyanogenmod based on android 4.4.4. какие ещё нужны данные?

**Comment by teod0r** [comment] 2017-01-30 18:34
где брать эти build.bootloader: ?

**Comment by VeryBadGuy** [comment] 2017-01-31 05:00
After updating to version 0.5, this error also appeared on my device.
Chuwi V88S, Android 4.4.2, ART runtime.

>ro.build.id=KOT49H
ro.build.display.id=rk3188-eng 4.4.2 KOT49H eng.bob.20140416.174825 test-keys
ro.build.version.incremental=eng.bob.20140416.174825
ro.build.version.sdk=19
ro.build.version.codename=REL
ro.build.version.release=4.4.2
ro.build.date=2014年 04月 16日 星期三 17:52:06 CST
ro.build.date.utc=1397641926
ro.build.type=eng
ro.build.user=bob
ro.build.host=bob-desktop
ro.build.tags=test-keys
ro.product.model=CW-V88S
ro.product.brand=ChuWi
ro.product.name=rk3188
ro.product.device=rk3188
ro.product.board=rk30sdk
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.manufacturer=rockchip
ro.product.locale.language=zh
ro.product.locale.region=CN
ro.board.platform=rk3188
ro.build.product=rk3188
ro.build.description=rk3188-eng 4.4.2 KOT49H eng.bob.20140416.174825 test-keys
ro.build.fingerprint=rockchip/rk3188/rk3188:4.4.2/KOT49H/eng.bob.20140416.174825:eng/test-keys
ro.build.characteristics=tablet


>01-31 12:15:09.670 I/ActivityManager(  460): START u0 {cmp=com.github.yeriomin.yalpstore/.PreferenceActivity} from pid 31765
01-31 12:15:09.900 E/AndroidRuntime(31765): Process: com.github.yeriomin.yalpstore, PID: 31765
01-31 12:15:09.900 E/AndroidRuntime(31765): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.yeriomin.yalpstore/com.github.yeriomin.yalpstore.PreferenceActivity}: android.view.InflateException: Binary XML file line #22: Error inflating class java.lang.reflect.Constructor
01-31 12:15:09.900 E/AndroidRuntime(31765):     at com.github.yeriomin.yalpstore.PreferenceActivity.onCreate(PreferenceActivity.java:36)
01-31 12:15:09.900 E/AndroidRuntime(31765):     at com.github.yeriomin.yalpstore.MultiSelectListPreference.onGetDefaultValue(MultiSelectListPreference.java:220)
01-31 12:15:09.900 E/AndroidRuntime(31765):     at com.github.yeriomin.yalpstore.MultiSelectListPreference.<init>(MultiSelectListPreference.java:32)
01-31 12:15:09.920 W/ActivityManager(  460):   Force finishing activity com.github.yeriomin.yalpstore/.PreferenceActivity
01-31 12:15:10.220 I/WindowManager(  460): Screenshot max retries 4 of Token{65173d10 ActivityRecord{64de9990 u0 com.github.yeriomin.yalpstore/.PreferenceActivity t917 f}} appWin=Window{64f43d30 u0 Starting com.github.yeriomin.yalpstore} drawState=4
01-31 12:15:10.220 W/ActivityManager(  460):   Force finishing activity com.github.yeriomin.yalpstore/.UpdatableAppsActivity
01-31 12:15:10.720 W/ActivityManager(  460): Activity pause timeout for ActivityRecord{64de9990 u0 com.github.yeriomin.yalpstore/.PreferenceActivity t917 f}
01-31 12:15:11.490 W/InputDispatcher(  460): channel '64d4dba8 com.github.yeriomin.yalpstore/com.github.yeriomin.yalpstore.UpdatableAppsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-31 12:15:11.490 E/InputDispatcher(  460): channel '64d4dba8 com.github.yeriomin.yalpstore/com.github.yeriomin.yalpstore.UpdatableAppsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-31 12:15:11.490 I/ActivityManager(  460): Process com.github.yeriomin.yalpstore (pid 31765) has died.
01-31 12:15:11.580 W/InputDispatcher(  460): Attempted to unregister already unregistered input channel '64d4dba8 com.github.yeriomin.yalpstore/com.github.yeriomin.yalpstore.UpdatableAppsActivity (server)'
01-31 12:15:11.580 I/WindowState(  460): WIN DEATH: Window{64d4dba8 u0 com.github.yeriomin.yalpstore/com.github.yeriomin.yalpstore.UpdatableAppsActivity}

**Comment by yeriomin** [comment] 2017-01-31 18:04
Fix is in v0.6. Tagged it just now, so it will be in f-droid in a couple of days.

**Closed by yeriomin** 2017-01-31 18:04 UTC
