### ISSUE TITLE
system apps setting is not respected

### ISSUE THREAD

**Issue by gerroon** [yeriomin/YalpStore#300] opened 2017-10-11 20:11 UTC
Hi

I have system apps disabled (show system apps is not checked) in the settings  however Yalp is still isting them in my apps and in updates.

This just started happening since the last update. It ws fine before.

I am using it on Lollipop 5.1 using Fdroid 0.27

thanks

**Comment by Primokorn** [comment] 2017-10-12 07:47
No issue here.
Did you try to check then uncheck the option or to clear app data?

**Comment by gerroon** [comment] 2017-10-12 14:04
yeah i did check uncheck but I did not try the clearing. thanks

**Comment by yeriomin** [comment] 2017-10-14 10:04
So is the issue resolved?

To be clear: system apps can be hidden on the installed apps list page only.

**Comment by narwanr** [comment] 2017-10-14 10:55
I have the same problem since updating to 0.27, and the issue persists in 0.28. It was fine in 0.26.

"Show system apps" is not checked, and system apps are not shown under "Your apps". However, system apps are shown under "Updates" which is really annoying.

Also, it would be more consistent to rename the option to "Hide system apps" and place it under "Search filtering" in the settings dialog.

**Comment by gerroon** [comment] 2017-10-14 16:08
No my issue is not resolved. System apps is shown regardless of the status of the settings provided for it.

**Comment by yeriomin** [comment] 2017-11-03 15:40
@gerroon Should be fixed in 0.29, which will be out in a couple of days.

@ghost

> However, system apps are shown under "Updates" which is really annoying.

That is intended behavior. There is no reason to hide updates for system apps. There are plenty of options to make individual apps (system or not) not show up in updates.

> Also, it would be more consistent to rename the option to "Hide system apps" and place it under "Search filtering" in the settings.

Since it is not search filtering it wouldn't be consistent.

**Closed by yeriomin** 2017-11-03 15:40 UTC

**Comment by gerroon** [comment] 2017-11-07 04:31
I think that the fix just broke the app.


Currently it only lists couple system apps when I check for updates regardless of sys apps is enabled or disabled.

I am able to get a full updates if I clean the cache, next time I start Yalp it is back to listing couple system app sonly again

**Comment by gerroon** [comment] 2017-11-07 04:34
I meant cleaning cache and data (not just chache)

**Comment by yeriomin** [comment] 2017-11-09 17:45
@gerroon Please reproduce it and send me a bug report from the Yalp Store main menu. Put your username or this issue number there.

**Comment by gerroon** [comment] 2017-11-09 18:29
I will. 

It sounds like the signing it with yalp account is not happening when I open the app. If I open the app then click on an existing app(without check for updates), then yalp tries to sign in with the its own creds then the update check works.
